"""
--- Part Two ---

With your analysis of the manifold complete, you begin fixing the teleporter. However, as you open the side of the teleporter to replace the broken manifold, you are surprised to discover that it isn't a classical tachyon manifold - it's a quantum tachyon manifold.

With a quantum tachyon manifold, only a single tachyon particle is sent through the manifold. A tachyon particle takes both the left and right path of each splitter encountered.

Since this is impossible, the manual recommends the many-worlds interpretation of quantum tachyon splitting: each time a particle reaches a splitter, it's actually time itself which splits. In one timeline, the particle went left, and in the other timeline, the particle went right.

To fix the manifold, what you really need to know is the number of timelines active after a single particle completes all of its possible journeys through the manifold.

In the above example, there are many timelines. For instance, there's the timeline where the particle always went left:

.......S.......
.......|.......
......|^.......
......|........
.....|^.^......
.....|.........
....|^.^.^.....
....|..........
...|^.^...^....
...|...........
..|^.^...^.^...
..|............
.|^...^.....^..
.|.............
|^.^.^.^.^...^.
|..............

Or, there's the timeline where the particle alternated going left and right at each splitter:

.......S.......
.......|.......
......|^.......
......|........
......^|^......
.......|.......
.....^|^.^.....
......|........
....^.^|..^....
.......|.......
...^.^.|.^.^...
.......|.......
..^...^|....^..
.......|.......
.^.^.^|^.^...^.
......|........

Or, there's the timeline where the particle ends up at the same point as the alternating timeline, but takes a totally different path to get there:

.......S.......
.......|.......
......|^.......
......|........
.....|^.^......
.....|.........
....|^.^.^.....
....|..........
....^|^...^....
.....|.........
...^.^|..^.^...
......|........
..^..|^.....^..
.....|.........
.^.^.^|^.^...^.
......|........

In this example, in total, the particle ends up on 40 different timelines.

Apply the many-worlds interpretation of quantum tachyon splitting to your manifold diagram. In total, how many different timelines would a single tachyon particle end up on?
"""

from collections import defaultdict

total_timelines = 0

with open('2025/07.txt', 'r') as f:
    lines = [line.rstrip('\n') for line in f]

# 1. Troviamo la posizione iniziale S nella prima riga
beams = defaultdict(int) # Mappa: x -> numero di particelle/linee temporali
start_x = lines[0].find('S')
beams[start_x] = 1

height = len(lines)
width = len(lines[0])

# 2. Iteriamo attraverso tutte le righe
for y in range(height):
    next_beams = defaultdict(int)
    row_str = lines[y]

    for x, count in beams.items():
        # Se per qualche motivo siamo fuori dalla griglia laterale (non dovrebbe succedere se gestito sotto)
        if x < 0 or x >= width:
            total_timelines += count
            continue

        char = row_str[x]

        # Determina le destinazioni per la riga successiva (y+1)
        targets = []
        if char == '^':
            # Splitter: il tempo si divide. Le copie vanno a sinistra e destra.
            targets = [x - 1, x + 1]
        else:
            # Spazio vuoto (.) o Start (S): il raggio continua dritto
            targets = [x]

        # Processa le destinazioni
        for tx in targets:
            # Se la destinazione è ancora dentro i bordi laterali della mappa
            if 0 <= tx < width:
                next_beams[tx] += count
            else:
                # Se esce dai lati, il viaggio è concluso (linea temporale valida)
                total_timelines += count

    # Passiamo alla riga successiva
    beams = next_beams

# 3. Alla fine del ciclo, 'beams' contiene le particelle che sono uscite dal fondo della mappa
total_timelines += sum(beams.values())

print(total_timelines)
